class Pieza3D {
    + int Id
    + string Nombre
    + string Descripcion
    + decimal Peso
    + string Modelo3DUrl
    + double PrecioEstimado
    + CategoriaPieza Categoria
    + int CategoriaId
}